# The variables are extracted from the POM file
requiresAsap: true
name: "@project.name@"
description: "@project.description@"
organization: "Commerce - CTO - CCP"
network:
  ingress: internal
links:
  healthcheck:
    uri: /heartbeat
    port: 8080
notifications:
  email: "atiwari6@atlassian.com"
buildNumber: "@build.timestamp@"

# NOTE: You will need to update this to match your service as you build it out
computeClassification:
  dataType:
    - None

compose:
  @project.artifactId@:
    image: docker.atl-paas.net/@docker.namespace@/@project.artifactId@
    tag: "@git.commit.id@@docker.tag.suffix@"
    ports:
      - 8080:8080
      - 9010:9010

scaling:
  instance: t3.small # Change this to a different instance if required, go/instance-types


config:
  environmentVariables:
    # See https://aws.amazon.com/ec2/instance-types/ for actual memory available for each instance type
    MEMORY_OPTS: "-XX:MaxRAMPercentage=25.0" # 25% of system memory

# See https://bitbucket.org/atlassian/ps-docker-base/src/master/ for information on how to:
# - Enable JMX metrics collection
# - Enable file crash dump and error log uploading to S3
# - Flamegraph support
# - New relic support

environmentOverrides:
  staging:
    resources:
      #Enable chaos engineering by default in staging environments
      - type: faila
        name: approx-one-termination-in-24-hours
        attributes:
          type: termination
          schedule: "0 0 * * * ?"
          probability: 4

  local:
    compose:
      @project.artifactId@:
        image: docker.atl-paas.net/@docker.namespace@/@project.artifactId@
        tag: "@git.commit.id@@docker.tag.suffix@"
        ports:
          - 8080:8080
          - 9010:9010
    
    config:
      environmentVariables:
        MEMORY_OPTS: "-Xmx512M"
